action_id: trunk-share-with-everyone
date: 2024-01-21 13:24:49
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1705843489
full_timestamp:
  nanos: 573246000
  seconds: 1705843489
trunk_version: 1.19.0
